title: My Journey into CyberSecurity
author: Jomar Rivera
email: jrsec22@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just an aspiring CyberSecurity professional learning how to make
  a website using github pages. I may populate this area with a resume
  and writeups along my journey at a later time. Thank you for viewing.
  
  
# social links
twitter_username: jrsec22 # DO NOT include the @ character, or else the build will fail!
github_username:  jrsec22 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
